# SPDX-FileCopyrightText: (C) 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-FileContributor: yyjeqhc <jialin.oerv@isrc.iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%global crate_name windows-sys
%global full_version 0.60.2
%global pkgname windows-sys-0.60

%define _source_payload w9.xzdio
%define _binary_payload w9.xzdio
%global _local_file_attrs rustcrates_feature
%global __rustcrates_feature_path ^%{_datadir}/cargo/registry/%{crate_name}-%{version}/\.rpm/features/[^/]+\.rpmdeps$
%global __rustcrates_feature_protocol singlefile
%global __rustcrates_feature_requires %rustcrates_depgen_helper --requires
%global __rustcrates_feature_provides %rustcrates_depgen_helper --provides

Name:           rust-windows-sys-0.60
Version:        0.60.2
Release:        %autorelease
Summary:        Rust crate "windows-sys"
License:        MIT OR Apache-2.0
URL:            https://github.com/microsoft/windows-rs
#!RemoteAsset:  sha256:f2f500e4d28234f72040990ec9d39e3a6b950f9f22d3dba18416c35882612bcb
Source:         https://crates.io/api/v1/crates/%{crate_name}/%{full_version}/download#/%{name}-%{version}.tar.gz
BuildArch:      noarch
BuildSystem:    rustcrates

BuildRequires:  rust-rpm-macros
BuildRequires:  takopack

Requires:       crate(windows-targets-0.53) >= 0.53.5
Provides:       crate(%{pkgname})
Provides:       crate(%{pkgname}/wdk)
Provides:       crate(%{pkgname}/wdk-devices)
Provides:       crate(%{pkgname}/wdk-devices-bluetooth)
Provides:       crate(%{pkgname}/wdk-devices-humaninterfacedevice)
Provides:       crate(%{pkgname}/wdk-foundation)
Provides:       crate(%{pkgname}/wdk-graphics)
Provides:       crate(%{pkgname}/wdk-graphics-direct3d)
Provides:       crate(%{pkgname}/wdk-networkmanagement)
Provides:       crate(%{pkgname}/wdk-networkmanagement-ndis)
Provides:       crate(%{pkgname}/wdk-networkmanagement-windowsfilteringplatform)
Provides:       crate(%{pkgname}/wdk-storage)
Provides:       crate(%{pkgname}/wdk-storage-filesystem)
Provides:       crate(%{pkgname}/wdk-storage-filesystem-minifilters)
Provides:       crate(%{pkgname}/wdk-system)
Provides:       crate(%{pkgname}/wdk-system-io)
Provides:       crate(%{pkgname}/wdk-system-memory)
Provides:       crate(%{pkgname}/wdk-system-offlineregistry)
Provides:       crate(%{pkgname}/wdk-system-registry)
Provides:       crate(%{pkgname}/wdk-system-systeminformation)
Provides:       crate(%{pkgname}/wdk-system-systemservices)
Provides:       crate(%{pkgname}/wdk-system-threading)
Provides:       crate(%{pkgname}/win32)
Provides:       crate(%{pkgname}/win32-data)
Provides:       crate(%{pkgname}/win32-data-htmlhelp)
Provides:       crate(%{pkgname}/win32-data-rightsmanagement)
Provides:       crate(%{pkgname}/win32-devices)
Provides:       crate(%{pkgname}/win32-devices-alljoyn)
Provides:       crate(%{pkgname}/win32-devices-beep)
Provides:       crate(%{pkgname}/win32-devices-biometricframework)
Provides:       crate(%{pkgname}/win32-devices-bluetooth)
Provides:       crate(%{pkgname}/win32-devices-cdrom)
Provides:       crate(%{pkgname}/win32-devices-communication)
Provides:       crate(%{pkgname}/win32-devices-deviceanddriverinstallation)
Provides:       crate(%{pkgname}/win32-devices-devicequery)
Provides:       crate(%{pkgname}/win32-devices-display)
Provides:       crate(%{pkgname}/win32-devices-dvd)
Provides:       crate(%{pkgname}/win32-devices-enumeration)
Provides:       crate(%{pkgname}/win32-devices-enumeration-pnp)
Provides:       crate(%{pkgname}/win32-devices-fax)
Provides:       crate(%{pkgname}/win32-devices-humaninterfacedevice)
Provides:       crate(%{pkgname}/win32-devices-nfc)
Provides:       crate(%{pkgname}/win32-devices-nfp)
Provides:       crate(%{pkgname}/win32-devices-portabledevices)
Provides:       crate(%{pkgname}/win32-devices-properties)
Provides:       crate(%{pkgname}/win32-devices-pwm)
Provides:       crate(%{pkgname}/win32-devices-sensors)
Provides:       crate(%{pkgname}/win32-devices-serialcommunication)
Provides:       crate(%{pkgname}/win32-devices-tapi)
Provides:       crate(%{pkgname}/win32-devices-usb)
Provides:       crate(%{pkgname}/win32-devices-webservicesondevices)
Provides:       crate(%{pkgname}/win32-foundation)
Provides:       crate(%{pkgname}/win32-gaming)
Provides:       crate(%{pkgname}/win32-globalization)
Provides:       crate(%{pkgname}/win32-graphics)
Provides:       crate(%{pkgname}/win32-graphics-dwm)
Provides:       crate(%{pkgname}/win32-graphics-gdi)
Provides:       crate(%{pkgname}/win32-graphics-gdiplus)
Provides:       crate(%{pkgname}/win32-graphics-hlsl)
Provides:       crate(%{pkgname}/win32-graphics-opengl)
Provides:       crate(%{pkgname}/win32-graphics-printing)
Provides:       crate(%{pkgname}/win32-graphics-printing-printticket)
Provides:       crate(%{pkgname}/win32-management)
Provides:       crate(%{pkgname}/win32-management-mobiledevicemanagementregistration)
Provides:       crate(%{pkgname}/win32-media)
Provides:       crate(%{pkgname}/win32-media-audio)
Provides:       crate(%{pkgname}/win32-media-dxmediaobjects)
Provides:       crate(%{pkgname}/win32-media-kernelstreaming)
Provides:       crate(%{pkgname}/win32-media-multimedia)
Provides:       crate(%{pkgname}/win32-media-streaming)
Provides:       crate(%{pkgname}/win32-media-windowsmediaformat)
Provides:       crate(%{pkgname}/win32-networkmanagement)
Provides:       crate(%{pkgname}/win32-networkmanagement-dhcp)
Provides:       crate(%{pkgname}/win32-networkmanagement-dns)
Provides:       crate(%{pkgname}/win32-networkmanagement-internetconnectionwizard)
Provides:       crate(%{pkgname}/win32-networkmanagement-iphelper)
Provides:       crate(%{pkgname}/win32-networkmanagement-multicast)
Provides:       crate(%{pkgname}/win32-networkmanagement-ndis)
Provides:       crate(%{pkgname}/win32-networkmanagement-netbios)
Provides:       crate(%{pkgname}/win32-networkmanagement-netmanagement)
Provides:       crate(%{pkgname}/win32-networkmanagement-netshell)
Provides:       crate(%{pkgname}/win32-networkmanagement-networkdiagnosticsframework)
Provides:       crate(%{pkgname}/win32-networkmanagement-p2p)
Provides:       crate(%{pkgname}/win32-networkmanagement-qos)
Provides:       crate(%{pkgname}/win32-networkmanagement-rras)
Provides:       crate(%{pkgname}/win32-networkmanagement-snmp)
Provides:       crate(%{pkgname}/win32-networkmanagement-wnet)
Provides:       crate(%{pkgname}/win32-networkmanagement-webdav)
Provides:       crate(%{pkgname}/win32-networkmanagement-wifi)
Provides:       crate(%{pkgname}/win32-networkmanagement-windowsconnectionmanager)
Provides:       crate(%{pkgname}/win32-networkmanagement-windowsfilteringplatform)
Provides:       crate(%{pkgname}/win32-networkmanagement-windowsfirewall)
Provides:       crate(%{pkgname}/win32-networkmanagement-windowsnetworkvirtualization)
Provides:       crate(%{pkgname}/win32-networking)
Provides:       crate(%{pkgname}/win32-networking-activedirectory)
Provides:       crate(%{pkgname}/win32-networking-clustering)
Provides:       crate(%{pkgname}/win32-networking-httpserver)
Provides:       crate(%{pkgname}/win32-networking-ldap)
Provides:       crate(%{pkgname}/win32-networking-websocket)
Provides:       crate(%{pkgname}/win32-networking-winhttp)
Provides:       crate(%{pkgname}/win32-networking-wininet)
Provides:       crate(%{pkgname}/win32-networking-winsock)
Provides:       crate(%{pkgname}/win32-networking-windowswebservices)
Provides:       crate(%{pkgname}/win32-security)
Provides:       crate(%{pkgname}/win32-security-applocker)
Provides:       crate(%{pkgname}/win32-security-authentication)
Provides:       crate(%{pkgname}/win32-security-authentication-identity)
Provides:       crate(%{pkgname}/win32-security-authorization)
Provides:       crate(%{pkgname}/win32-security-credentials)
Provides:       crate(%{pkgname}/win32-security-cryptography)
Provides:       crate(%{pkgname}/win32-security-cryptography-catalog)
Provides:       crate(%{pkgname}/win32-security-cryptography-certificates)
Provides:       crate(%{pkgname}/win32-security-cryptography-sip)
Provides:       crate(%{pkgname}/win32-security-cryptography-ui)
Provides:       crate(%{pkgname}/win32-security-diagnosticdataquery)
Provides:       crate(%{pkgname}/win32-security-directoryservices)
Provides:       crate(%{pkgname}/win32-security-enterprisedata)
Provides:       crate(%{pkgname}/win32-security-extensibleauthenticationprotocol)
Provides:       crate(%{pkgname}/win32-security-isolation)
Provides:       crate(%{pkgname}/win32-security-licenseprotection)
Provides:       crate(%{pkgname}/win32-security-networkaccessprotection)
Provides:       crate(%{pkgname}/win32-security-wintrust)
Provides:       crate(%{pkgname}/win32-security-winwlx)
Provides:       crate(%{pkgname}/win32-storage)
Provides:       crate(%{pkgname}/win32-storage-cabinets)
Provides:       crate(%{pkgname}/win32-storage-cloudfilters)
Provides:       crate(%{pkgname}/win32-storage-compression)
Provides:       crate(%{pkgname}/win32-storage-distributedfilesystem)
Provides:       crate(%{pkgname}/win32-storage-filehistory)
Provides:       crate(%{pkgname}/win32-storage-filesystem)
Provides:       crate(%{pkgname}/win32-storage-imapi)
Provides:       crate(%{pkgname}/win32-storage-indexserver)
Provides:       crate(%{pkgname}/win32-storage-installablefilesystems)
Provides:       crate(%{pkgname}/win32-storage-iscsidisc)
Provides:       crate(%{pkgname}/win32-storage-jet)
Provides:       crate(%{pkgname}/win32-storage-nvme)
Provides:       crate(%{pkgname}/win32-storage-offlinefiles)
Provides:       crate(%{pkgname}/win32-storage-operationrecorder)
Provides:       crate(%{pkgname}/win32-storage-packaging)
Provides:       crate(%{pkgname}/win32-storage-packaging-appx)
Provides:       crate(%{pkgname}/win32-storage-projectedfilesystem)
Provides:       crate(%{pkgname}/win32-storage-structuredstorage)
Provides:       crate(%{pkgname}/win32-storage-vhd)
Provides:       crate(%{pkgname}/win32-storage-xps)
Provides:       crate(%{pkgname}/win32-system)
Provides:       crate(%{pkgname}/win32-system-addressbook)
Provides:       crate(%{pkgname}/win32-system-antimalware)
Provides:       crate(%{pkgname}/win32-system-applicationinstallationandservicing)
Provides:       crate(%{pkgname}/win32-system-applicationverifier)
Provides:       crate(%{pkgname}/win32-system-clrhosting)
Provides:       crate(%{pkgname}/win32-system-com)
Provides:       crate(%{pkgname}/win32-system-com-marshal)
Provides:       crate(%{pkgname}/win32-system-com-structuredstorage)
Provides:       crate(%{pkgname}/win32-system-com-urlmon)
Provides:       crate(%{pkgname}/win32-system-componentservices)
Provides:       crate(%{pkgname}/win32-system-console)
Provides:       crate(%{pkgname}/win32-system-correlationvector)
Provides:       crate(%{pkgname}/win32-system-dataexchange)
Provides:       crate(%{pkgname}/win32-system-deploymentservices)
Provides:       crate(%{pkgname}/win32-system-developerlicensing)
Provides:       crate(%{pkgname}/win32-system-diagnostics)
Provides:       crate(%{pkgname}/win32-system-diagnostics-ceip)
Provides:       crate(%{pkgname}/win32-system-diagnostics-debug)
Provides:       crate(%{pkgname}/win32-system-diagnostics-debug-extensions)
Provides:       crate(%{pkgname}/win32-system-diagnostics-etw)
Provides:       crate(%{pkgname}/win32-system-diagnostics-processsnapshotting)
Provides:       crate(%{pkgname}/win32-system-diagnostics-toolhelp)
Provides:       crate(%{pkgname}/win32-system-diagnostics-tracelogging)
Provides:       crate(%{pkgname}/win32-system-distributedtransactioncoordinator)
Provides:       crate(%{pkgname}/win32-system-environment)
Provides:       crate(%{pkgname}/win32-system-errorreporting)
Provides:       crate(%{pkgname}/win32-system-eventcollector)
Provides:       crate(%{pkgname}/win32-system-eventlog)
Provides:       crate(%{pkgname}/win32-system-eventnotificationservice)
Provides:       crate(%{pkgname}/win32-system-grouppolicy)
Provides:       crate(%{pkgname}/win32-system-hostcompute)
Provides:       crate(%{pkgname}/win32-system-hostcomputenetwork)
Provides:       crate(%{pkgname}/win32-system-hostcomputesystem)
Provides:       crate(%{pkgname}/win32-system-hypervisor)
Provides:       crate(%{pkgname}/win32-system-io)
Provides:       crate(%{pkgname}/win32-system-iis)
Provides:       crate(%{pkgname}/win32-system-ioctl)
Provides:       crate(%{pkgname}/win32-system-jobobjects)
Provides:       crate(%{pkgname}/win32-system-js)
Provides:       crate(%{pkgname}/win32-system-kernel)
Provides:       crate(%{pkgname}/win32-system-libraryloader)
Provides:       crate(%{pkgname}/win32-system-mailslots)
Provides:       crate(%{pkgname}/win32-system-mapi)
Provides:       crate(%{pkgname}/win32-system-memory)
Provides:       crate(%{pkgname}/win32-system-memory-nonvolatile)
Provides:       crate(%{pkgname}/win32-system-messagequeuing)
Provides:       crate(%{pkgname}/win32-system-mixedreality)
Provides:       crate(%{pkgname}/win32-system-ole)
Provides:       crate(%{pkgname}/win32-system-passwordmanagement)
Provides:       crate(%{pkgname}/win32-system-performance)
Provides:       crate(%{pkgname}/win32-system-performance-hardwarecounterprofiling)
Provides:       crate(%{pkgname}/win32-system-pipes)
Provides:       crate(%{pkgname}/win32-system-power)
Provides:       crate(%{pkgname}/win32-system-processstatus)
Provides:       crate(%{pkgname}/win32-system-recovery)
Provides:       crate(%{pkgname}/win32-system-registry)
Provides:       crate(%{pkgname}/win32-system-remotedesktop)
Provides:       crate(%{pkgname}/win32-system-remotemanagement)
Provides:       crate(%{pkgname}/win32-system-restartmanager)
Provides:       crate(%{pkgname}/win32-system-restore)
Provides:       crate(%{pkgname}/win32-system-rpc)
Provides:       crate(%{pkgname}/win32-system-search)
Provides:       crate(%{pkgname}/win32-system-search-common)
Provides:       crate(%{pkgname}/win32-system-securitycenter)
Provides:       crate(%{pkgname}/win32-system-services)
Provides:       crate(%{pkgname}/win32-system-setupandmigration)
Provides:       crate(%{pkgname}/win32-system-shutdown)
Provides:       crate(%{pkgname}/win32-system-stationsanddesktops)
Provides:       crate(%{pkgname}/win32-system-subsystemforlinux)
Provides:       crate(%{pkgname}/win32-system-systeminformation)
Provides:       crate(%{pkgname}/win32-system-systemservices)
Provides:       crate(%{pkgname}/win32-system-threading)
Provides:       crate(%{pkgname}/win32-system-time)
Provides:       crate(%{pkgname}/win32-system-tpmbaseservices)
Provides:       crate(%{pkgname}/win32-system-useraccesslogging)
Provides:       crate(%{pkgname}/win32-system-variant)
Provides:       crate(%{pkgname}/win32-system-virtualdosmachines)
Provides:       crate(%{pkgname}/win32-system-windowsprogramming)
Provides:       crate(%{pkgname}/win32-system-wmi)
Provides:       crate(%{pkgname}/win32-ui)
Provides:       crate(%{pkgname}/win32-ui-accessibility)
Provides:       crate(%{pkgname}/win32-ui-colorsystem)
Provides:       crate(%{pkgname}/win32-ui-controls)
Provides:       crate(%{pkgname}/win32-ui-controls-dialogs)
Provides:       crate(%{pkgname}/win32-ui-hidpi)
Provides:       crate(%{pkgname}/win32-ui-input)
Provides:       crate(%{pkgname}/win32-ui-input-ime)
Provides:       crate(%{pkgname}/win32-ui-input-keyboardandmouse)
Provides:       crate(%{pkgname}/win32-ui-input-pointer)
Provides:       crate(%{pkgname}/win32-ui-input-touch)
Provides:       crate(%{pkgname}/win32-ui-input-xboxcontroller)
Provides:       crate(%{pkgname}/win32-ui-interactioncontext)
Provides:       crate(%{pkgname}/win32-ui-magnification)
Provides:       crate(%{pkgname}/win32-ui-shell)
Provides:       crate(%{pkgname}/win32-ui-shell-common)
Provides:       crate(%{pkgname}/win32-ui-shell-propertiessystem)
Provides:       crate(%{pkgname}/win32-ui-tabletpc)
Provides:       crate(%{pkgname}/win32-ui-textservices)
Provides:       crate(%{pkgname}/win32-ui-windowsandmessaging)
Provides:       crate(%{pkgname}/win32-web)
Provides:       crate(%{pkgname}/win32-web-internetexplorer)
Provides:       crate(%{pkgname}/default)
Provides:       crate(%{pkgname}/docs)

%description
Source code for takopackized Rust crate "windows-sys"

%files
%exclude %{_datadir}/cargo/registry/%{crate_name}-%{version}/.rpm/features/*.rpmdeps
%{_datadir}/cargo/registry/%{crate_name}-%{version}/

%changelog
%autochangelog
