# SPDX-FileCopyrightText: (C) 2025, 2026 Institute of Software, Chinese Academy of Sciences (ISCAS)
# SPDX-FileCopyrightText: (C) 2025, 2026 openRuyi Project Contributors
# SPDX-FileContributor: misaka00251 <liuxin@iscas.ac.cn>
#
# SPDX-License-Identifier: MulanPSL-2.0

%global srcname ruamel.yaml.clib

Name:           python-ruamel-yaml-clib
Version:        0.2.15
Release:        %autorelease
Summary:        C version of reader, parser and emitter for ruamel.yaml derived from libyaml
License:        MIT
URL:            https://sourceforge.net/projects/ruamel-yaml-clib/
#Source0:        https://files.pythonhosted.org/packages/source/r/%%{srcname}/%%{srcname}-%{version}.tar.gz
#!RemoteAsset
Source0:        https://yaml.dev/ruamel-dl-tagged-releases/%{srcname}-%{version}.tar.xz
BuildSystem:    pyproject

BuildOption(install):  -l _ruamel_yaml
BuildOption(check):  _ruamel_yaml

BuildRequires:  pyproject-rpm-macros
BuildRequires:  pkgconfig(python3)
BuildRequires:  python3dist(cython)
# For %check
BuildRequires:  python3dist(ruamel-yaml)

Provides:       python3-ruamel-yaml-clib
%python_provide python3-ruamel-yaml-clib

Requires:       python3dist(ruamel-yaml)

%description
ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of
comments, seq/map flow style, and map key order.
This package contains the C library counterpart of it.

%prep -a
# Force regenerating C files from Cython sources
rm -v $(grep -rl '/\* Generated by Cython')

%generate_buildrequires
%pyproject_buildrequires

%build -p
# cython refuses to cythonize a file in a directory that cannot be a Python
# module ¯\_(ツ)_/¯
#
# Top-level structure seems to be incompatible with Cython 0.29.34
# ('ruamel-yaml-clib-code._ruamel_yaml' is not a valid module name)
# https://sourceforge.net/p/ruamel-yaml-clib/tickets/14/
mkdir ruamel.yaml.clib
mv *.pyx ruamel.yaml.clib
cythonize -j${RPM_BUILD_NCPUS} -3 ruamel.yaml.clib/*.pyx
mv ruamel.yaml.clib/* .
rmdir ruamel.yaml.clib

%files -f %{pyproject_files}
%doc README.md

%changelog
%{?autochangelog}
