# see src/bootstrap/src/utils/change_tracker.rs
change-id = 146435

[llvm]
download-ci-llvm = false
link-shared = true

[build]
tools = [
    "cargo",
    "clippy",
    "rustdoc",
    "rustfmt",
    "rust-analyzer",
    "rust-analyzer-proc-macro-srv",
    "analysis",
    "src",
    "wasm-component-ld",
    "miri", "cargo-miri" # for dev/nightly channels
]

target = [
  "x86_64-unknown-linux-gnu",
  "riscv64gc-unknown-linux-gnu",
]

locked-deps = true
vendor = true
submodules = false

cargo = "/usr/bin/cargo"
rustc = "/usr/bin/rustc"
rustfmt = "/usr/bin/rustfmt"
cargo-clippy = "/usr/bin/cargo-clippy"

[rust]
strip = false
download-rustc = false
channel = "stable"
rpath = false
frame-pointers = true

[install]
prefix = "/usr"

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"
[target.riscv64gc-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"
